<a href="https://colab.research.google.com/github/danielhendra0046/kelas-terbuka-python-dasar/blob/main/kelas_terbuka_python_dasar_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello")

Hello


# 30 OKTOBER 2023

## Operasi List

In [ ]:
# count digunakan untuk menghitung jumlah data

data_angka = [1,5,1,4,3,2,4,3,2,2,6,8,9,0,6]

jumlah_data_4 = data_angka.count(4)
jumlah_data_3 = data_angka.count(3)

print(f"jumlah angka 4 = {jumlah_data_4}")
print(f"jumlah angka 3 = {jumlah_data_3}")

# cara mengurutkan angka, menggunakan .sort

data_angka.sort()
print(f"data angka setelah disort = \n{data_angka}")

# cara membalik urutan

data_angka.reverse()
print(f"data angka setelah direverse = \n{data_angka}")

jumlah angka 4 = 2
jumlah angka 3 = 2
data angka setelah disort = 
[0, 1, 1, 2, 2, 2, 3, 3, 4, 4, 5, 6, 6, 8, 9]
data angka setelah direverse = 
[9, 8, 6, 6, 5, 4, 4, 3, 3, 2, 2, 2, 1, 1, 0]


Lalu, ada lagi .index , digunakan untuk menghitung dia posisi data ke berapa di list

Lalu, gimana caranya copy list?

In [ ]:
data_angka = [1,5,1,4,3,2,4,3,2,2,6,8,9,0,6]

data_angka_new = data_angka.copy()

print(f"ini adalah data angka: \n{data_angka}")
print(f"ini adalah data angka setelah dicopy: \n{data_angka_new}")

data_angka_new[1] = 3

print(f"ini adalah data angka setelah diubah: \n{data_angka_new}")

ini adalah data angka: 
[1, 5, 1, 4, 3, 2, 4, 3, 2, 2, 6, 8, 9, 0, 6]
ini adalah data angka setelah dicopy: 
[1, 5, 1, 4, 3, 2, 4, 3, 2, 2, 6, 8, 9, 0, 6]
ini adalah data angka setelah diubah: 
[1, 3, 1, 4, 3, 2, 4, 3, 2, 2, 6, 8, 9, 0, 6]


Nested List -> list di dalam list

In [ ]:
data_0 = [1,2]
data_1 = [3,4,5]

list_2D = [data_0,data_1]

print(f"list 2D {list_2D}")

# contoh penggunaan

peserta_0 = ["Ucup",25,"Laki-laki"]
peserta_1 = ["Otong",10,"Laki-laki"]
peserta_2 = ["Dedeh",50,"Wanita"]

list_peserta = [peserta_0,peserta_1,peserta_2]

print(f"peserta = {list_peserta}")

for peserta in list_peserta:
  print(f"nama\t: {peserta[0]}")
  print(f"umur\t: {peserta[1]}")
  print(f"gender\t: {peserta[2]}\n")

list 2D [[1, 2], [3, 4, 5]]
peserta = [['Ucup', 25, 'Laki-laki'], ['Otong', 10, 'Laki-laki'], ['Dedeh', 50, 'Wanita']]
nama	: Ucup
umur	: 25
gender	: Laki-laki

nama	: Otong
umur	: 10
gender	: Laki-laki

nama	: Dedeh
umur	: 50
gender	: Wanita



kalau kita mengcopy data nested list, kita tidak bisa memakai cara biasa. Harus pakai deepcopy

In [ ]:
data_0 = [1,2]
data_1 = [3,4]

data_2D = [data_0,data_1]

from copy import deepcopy

data_2D_deepcopy = deepcopy(data_2D)

print(f"address asli = {hex(id(data_2D))}")
print(f"address deep = {hex(id(data_2D_deepcopy))}\n")

print("Address dari member ke-1")
print(f"address asli = {hex(id(data_2D[0]))}")
print(f"address deep = {hex(id(data_2D_deepcopy[0]))}")

address asli = 0x7bde07780a00
address deep = 0x7bde0777c600

Address dari member ke-1
address asli = 0x7bde07783940
address deep = 0x7bde0777c840


## Looping List dan Enumerate

# 31 OKTOBER 2023

## Looping List dan Eunumerate

cara looping list

In [ ]:
# looping list menggunakan for loop

print("For Loop")
kumpulan_angka = [4,3,2,5,6,1]

for angka in kumpulan_angka:
  print(f"angka = {angka}")

peserta = ["Ucup","Otong","Dadang","Diding"]

for nama in peserta:
  print(f'nama = {nama}')

# looping list menggunakan for loop dan range
print("\nFor Loop dan Range")
kumpulan_angka = [10,5,4,2,6,5]
panjang = len(kumpulan_angka)

for i in range(panjang):
  print(f"angka = {kumpulan_angka[i]}")

# looping list menggunakan while loop
print("\nWhile Loop")
kumpulan_angka = [10,5,4,2,6,5]

panjang = len(kumpulan_angka)
i = 0

while i < panjang:
  print(f"angka = {kumpulan_angka[i]}")
  i += 1

# looping list menggunakan list comprehension
print("\nList Comprehension")

data = ["Ucup",1,2,3,"Otong"]

[print(f"data = {i}") for i in data]


# looping list menggunakan list comprehension dikuadratkan
print("\nList Comprehension Dikuadratkan")
angka = [10,5,4,2,6,5]

angka_kuadrat = [i**2 for i in angka]
print(angka_kuadrat)

[print(f"data = {i**2}") for i in angka]

# looping list menggunakan enumerate
print("\nEnumerate")
data_list = ["Ucup",1,2,3,"Otong"]

for index,data in enumerate(data_list):
  print(f"index = {index}, data = {data}")

For Loop
angka = 4
angka = 3
angka = 2
angka = 5
angka = 6
angka = 1
nama = Ucup
nama = Otong
nama = Dadang
nama = Diding

For Loop dan Range
angka = 10
angka = 5
angka = 4
angka = 2
angka = 6
angka = 5

While Loop
angka = 10
angka = 5
angka = 4
angka = 2
angka = 6
angka = 5

List Comprehension
data = Ucup
data = 1
data = 2
data = 3
data = Otong

List Comprehension Dikuadratkan
[100, 25, 16, 4, 36, 25]
data = 100
data = 25
data = 16
data = 4
data = 36
data = 25

Enumerate
index = 0, data = Ucup
index = 1, data = 1
index = 2, data = 2
index = 3, data = 3
index = 4, data = Otong


## Latihan List

In [ ]:
# Program list buku

list_buku = []
while True:
  print("\nMasukan data buku")
  judul = input("Judul buku\t: ")
  penulis = input("Nama penulis\t ")

  buku_baru = [judul,penulis]
  list_buku.append(buku_baru)

  print("\n\n","="*10)
  for index,buku in enumerate(list_buku):
    print(f"{index+1} | {buku[0]} | {buku[1]}")

  print("\n\n","="*20)
  isLanjut = input("Apakah dilanjutkan?(y/n)")

  if isLanjut == "n":
    break

print("Program Selesai")


Masukan data buku
Judul buku	: hihi
Nama penulis	 haha


1 | hihi | haha


Apakah dilanjutkan?(y/n)y

Masukan data buku
Judul buku	: haha
Nama penulis	 hihi


1 | hihi | haha
2 | haha | hihi


Apakah dilanjutkan?(y/n)x

Masukan data buku
Judul buku	: hihi
Nama penulis	 huhu


1 | hihi | haha
2 | haha | hihi
3 | hihi | huhu


Apakah dilanjutkan?(y/n)n


## Tuples dan Set and Dictionary

biasanya kan kita mencatat list menggunakan [],

Tuples adalah list yang menggunakan tanda () -> tidak dapat ditambah atau dikurangi / dimodifikasi datanya

Sets adalah list yang menggunakan tanda {} -> tidak memiliki index / sama dengan himpunan dalam ilmu matematika

Kalau dictionary bagaimana?

In [ ]:
# Contoh dictionary

data_dict = {
    'key' : 'value',
    'cp' : 'ucup',
    'tg' : 'otong',
    'dg' : 'dudung'
}

print(data_dict['dg'])

dudung


Operator Dictionary

In [ ]:
data_dict = {
    'cup' : 'ucup surucup',
    'tong' : 'otong surotong',
    'dung' : 'dudung surudung',
}

# Panjang dictionary
LENDICT = len(data_dict)
print(f"panjang dictionary: {LENDICT}")

# Mengecek key exist atau tidak
KEY = "cup"
CHECKKEY = KEY in data_dict
print(f"apakah {KEY} ada di data_dict: {CHECKKEY}")

# Mengakses value dengan get
print("\nCARA MENGAKSES VALUE DENGAN GET")
print(data_dict["cup"])
print(data_dict.get("cup"))
print(data_dict.get("kis","key tidak ditemukan"))

print("\nCARA UPDATE DATA")
# mengupdate data
data_dict["cup"] = "ucup si ganteng"
print(data_dict)
data_dict["sep"] = "asep si kasyep"
print(data_dict)

data_dict.update({"cup":"ucup surucup"})
print(data_dict)
data_dict.update({"faqih":"faqihza si kweren"})
print(data_dict)

# mendelete data pada dictionary
print("\nCARA DELETE DATA")
del data_dict["faqih"]
print(data_dict)

panjang dictionary: 3
apakah cup ada di data_dict: True

CARA MENGAKSES VALUE DENGAN GET
ucup surucup
ucup surucup
key tidak ditemukan

CARA UPDATE DATA
{'cup': 'ucup si ganteng', 'tong': 'otong surotong', 'dung': 'dudung surudung'}
{'cup': 'ucup si ganteng', 'tong': 'otong surotong', 'dung': 'dudung surudung', 'sep': 'asep si kasyep'}
{'cup': 'ucup surucup', 'tong': 'otong surotong', 'dung': 'dudung surudung', 'sep': 'asep si kasyep'}
{'cup': 'ucup surucup', 'tong': 'otong surotong', 'dung': 'dudung surudung', 'sep': 'asep si kasyep', 'faqih': 'faqihza si kweren'}

CARA DELETE DATA
{'cup': 'ucup surucup', 'tong': 'otong surotong', 'dung': 'dudung surudung', 'sep': 'asep si kasyep'}


Looping Dictionary -> intinya bagaimana cara mengambil key, value, dan items di dalam dictionary

cara mengcopy dictionary menggunakan .copy <br>
cara mentransfer data dictionary menggunakan .pop , kalau .popitem itu mentransfer data yang paling terakhir

## Latihan Dictionary

In [ ]:
import datetime
import string
import random

mahasiswa_template = {
    'nama':'nama',
    'nim':'00000000',
    'sks_lulus':0,
    'lahir':datetime.datetime(1111,1,11)
}

data_mahasiswa = {}

while True:
  print(f"{'SELAMAT DATANG':^20}")
  print(f"{'DATA MAHASISWA':^20}")
  print("-"*20)

  mahasiswa = dict.fromkeys(mahasiswa_template.keys())
  mahasiswa['nama'] = input("Nama Mahasiswa: ")
  mahasiswa['nim'] = input("NIM Mahasiswa: ")
  mahasiswa['sks_lulus'] = int(input("SKS Lulus Mahasiswa: "))
  TAHUN_LAHIR = int(input("Tahun lahir (YYYY): "))
  BULAN_LAHIR = int(input("Bulan lahir (1-12): "))
  TANGGAL_LAHIR = int(input("Tanggal lahir (1-31): " ))
  mahasiswa['lahir'] = datetime.datetime(TAHUN_LAHIR,BULAN_LAHIR,TANGGAL_LAHIR)

  KEY = ''.join((random.choice(string.ascii_uppercase) for i in range(6)))
  data_mahasiswa.update({KEY:mahasiswa})

  print(f"\n{'KEY':<6} {'Nama':<17} {'NIM':<8} {'SKS Lulus':<10} {'Tanggal Lahir':<10}")
  print('-'*60)

  for mahasiswa in data_mahasiswa:
    KEY = mahasiswa

    NAMA = data_mahasiswa[KEY]['nama']
    NIM = data_mahasiswa[KEY]['nim']
    SKS = data_mahasiswa[KEY]['sks_lulus']
    LAHIR = data_mahasiswa[KEY]['lahir'].strftime("%x")

    print(f"{KEY:<6} {NAMA:<17} {NIM:<8} {SKS:^10} {LAHIR:^10}")

  print("\n")
  is_done = input("Sudah beres bro? (y/n) ")
  if is_done == "n":
    break

print("\nAkhir dari program, terima kasih")

   SELAMAT DATANG   
   DATA MAHASISWA   
--------------------
Nama Mahasiswa: daniel
NIM Mahasiswa: 101019
SKS Lulus Mahasiswa: 144
Tahun lahir (YYYY): 2000
Bulan lahir (1-12): 08
Tanggal lahir (1-31): 07

KEY    Nama              NIM      SKS Lulus  Tanggal Lahir
------------------------------------------------------------
BZFAHA daniel            101019      144      08/07/00 


Sudah beres bro? (y/n) n

Akhir dari program, terima kasih


## Fungsi

Berguna untuk menyederhanakan codingan

In [ ]:
def hello_world(nama):
  print(f"Hallo {nama}")

hello_world("ucup")

# program tambah
print('-'*10)

def tambah(angka_1,angka_2):
  hasil = angka_1 + angka_2
  print(f"{angka_1} + {angka_2} = {hasil}")

tambah(1,5)

# ????
print('-'*10)

def say_hi(list_peserta):
  data_peserta = list_peserta.copy()
  for peserta in data_peserta:
    print(f"Yang terhormat {peserta}")

anggota_boyband = ["Ucup","Otong","Dudung"]

say_hi(anggota_boyband)


Hallo ucup
----------
1 + 5 = 6
----------
Yang terhormat Ucup
Yang terhormat Otong
Yang terhormat Dudung


Fungsi Return

In [ ]:
# Fungsi return biasa
def kuadrat(input_angka):
  output_kuadrat = input_angka**2
  return output_kuadrat

y = kuadrat(5)
print(y)

# Fungsi dengan return banyak
print('-'*10)

def operasi_matematika(angka_1,angka_2):
  tambah = angka_1 + angka_2
  kurang = angka_1 - angka_2
  kali = angka_1 * angka_2
  bagi = angka_1 / angka_2

  return tambah,kurang,kali,bagi

k,l,m,n = operasi_matematika(9,5)

print(f"Hasil tambah = {k}")
print(f"Hasil kurang = {l}")
print(f"Hasil kali = {m}")
print(f"Hasil bagi = {n}")

25
----------
Hasil tambah = 14
Hasil kurang = 4
Hasil kali = 45
Hasil bagi = 1.8


Default argument

In [ ]:
def say_hello(nama = "Ganteng"):
  print(f"Hallo {nama}")

say_hello("Ucup")
say_hello()

# dengan banyak parameter
print('-'*10)

def sapa_dia(nama, pesan = "Apa kabar?"):
  print(f"hai {nama}, {pesan}")

sapa_dia("Dudung","Hai Ganteeeng")
sapa_dia("Otong")
sapa_dia(nama="Ucup")

Hallo Ucup
Hallo Ganteng
----------
hai Dudung, Hai Ganteeeng
hai Otong, Apa kabar?
hai Ucup, Apa kabar?


## Latihan Fungsi

In [ ]:
'''Latihan Fungsi'''

import os

# Program menghitung luas dan keliling persegi panjang

# membuat header program

def header():
  '''Fungsi header'''
  os.system("clear")
  print(f"{'PROGRAM MENGHITUNG LUAS':^40}")
  print(f"{'DAN KELILIG PERSEGI PANJANG':^40}")
  print(f"{'-'*40:^40}")

def input_user():
  '''fungsi input user'''
  lebar = int(input("masukan nilai lebar: "))
  panjang = int(input("masukan nilai panjang: "))

  return lebar,panjang

def hitung_luas(lebar,panjang):
  '''fungsi luas'''
  return lebar*panjang

def hitung_keliling(lebar,panjang):
  '''fungsi luas'''
  return 2*(lebar+panjang)

def display(message,value):
  print(f"hasil perhitungan {message} = {value}")

while True:
  header()
  LEBAR,PANJANG = input_user()
  LUAS = hitung_luas(LEBAR,PANJANG)
  KELILING = hitung_keliling(LEBAR,PANJANG)

  display("luas", LUAS)
  display("keliling", KELILING)

  isContinue = input("apakah lanjut?(y/n)")
  if isContinue == "n":
    break

print("Program selesai, terima kasih!")

        PROGRAM MENGHITUNG LUAS         
      DAN KELILIG PERSEGI PANJANG       
----------------------------------------
masukan nilai lebar: 20
masukan nilai panjang: 30
hasil perhitungan luas = 600
hasil perhitungan keliling = 100
apakah lanjut?(y/n)y
        PROGRAM MENGHITUNG LUAS         
      DAN KELILIG PERSEGI PANJANG       
----------------------------------------
masukan nilai lebar: 49
masukan nilai panjang: 20
hasil perhitungan luas = 980
hasil perhitungan keliling = 138
apakah lanjut?(y/n)n
Program selesai, terima kasih!


# 1 NOVEMBER 2023

## Fungsi Lanjutan

Type hint cara penulisannya yaitu <br>
def sepuluh_pangkat(apapun:int) <br>
fungsinya agar dokumentasi kita rapi

Tentang *args

In [ ]:
def fungsi(*args): # bisa apapun, nggak harus args
   nama = args[0]
   tinggi = args[1]
   berat = args[2]
   print(f"{nama} punya tinggi {tinggi} dan berat {berat}")

fungsi("dudung",120,120)

dudung punya tinggi 120 dan berat 120


Tentang **kwargs

In [ ]:
# contoh biasa

def fungsi(**kwargs):
  '''fungsi kwargs'''
  print(kwargs["nama"])

fungsi(nama="ucup",tinggi=183,berat=79)

# contoh lain

def fungsi(**kwargs):
  '''fungsi kwargs'''
  nama = kwargs["nama"]
  tinggi = kwargs["tinggi"]
  berat = kwargs["berat"]
  print(f"{nama} punya tinggi {tinggi} dan berat {berat}")

fungsi(nama="ucup",tinggi=183,berat=79)

ucup
ucup punya tinggi 183 dan berat 79


In [ ]:
# studi kasus

def math(*args,**kwargs):
  output = 0
  if kwargs["option"] == "tambah":
    for angka in args:
      output += angka
  elif kwargs["option"] == "kali":
    output = 1
    for angka in args:
      output *= angka
  else:
    print("tidak ada operasi")

  return output

hasil = math(1,2,3,4,5,6,option="tambah")
print(f"hasil jumlah {hasil}")

hasil = math(1,2,3,4,5,6,option="kali")
print(f"hasil kali {hasil}")

hasil jumlah 21
hasil kali 720


## Lambda dan Anonymous Function

Fungsi lambda -> mengsimplekan codingan

In [ ]:
kuadrat = lambda angka : angka**2
print(f"hasil lambda kuadrat = {kuadrat(3)}")

hasil lambda kuadrat = 9


In [ ]:
pangkat = lambda num,pow : num**pow
print(f"hasil lambda pangkat = {pangkat(4,2)}")

hasil lambda pangkat = 16


In [ ]:
# sort pakai lambda

data_list = ["Otong","Ucup","Dudung"]
data_list.sort(key=lambda nama:len(nama))
print(f"sorted list by lambda = {data_list}")

print('-'*50)
# filter

data_angka = [1,2,3,4,5,6,7,8,9,10,11,12]

data_angka_baru = list(filter(lambda x:x<7,data_angka))
print(data_angka_baru)

sorted list by lambda = ['Ucup', 'Otong', 'Dudung']
--------------------------------------------------
[1, 2, 3, 4, 5, 6]


Anonymous Function

In [ ]:
# dengan currying

def pangkat(n):
  return lambda angka : angka**n

pangkat2 = pangkat(2)
print(f"pangkat2 = {pangkat2(5)}")
pangkat3 = pangkat(3)
print(f"pangkat3 = {pangkat3(5)}")

print(f"pangkat bebas = {pangkat(2)(3)}")

pangkat2 = 25
pangkat3 = 125
pangkat bebas = 9


Tentang Global dan Local Scope -> permasalahannya, variabel scope (yg di dalam function) biasanya tidak bisa dipakai untuk method yg di luar. Solusinya ....

In [ ]:
# mengubah variabel global

angka = 0

def ubah_angka(nilai_baru):
  global angka # pakai ini supaya bisa
  angka = nilai_baru

print(f"sebelum {angka}")
ubah_angka(10)
print(f"sesudah {angka}")

sebelum 0
sesudah 10


## Import Statement

In [ ]:
from collections import Counter

data = ["a","b","c","d","a","d","a"]
data_count = Counter(data)

print(f"data count = {data_count}")
print(f"jumlah a = {data_count['a']}")
print(f"jumlah b = {data_count['b']}")

data count = Counter({'a': 3, 'd': 2, 'b': 1, 'c': 1})
jumlah a = 3
jumlah b = 1


In [ ]:
import numpy as np

list_a = [1,2,3,4]
vector_a = np.array([1,2,3,4])

print(f"list_a = {list_a}")
print(f"vector_a = {vector_a}")

list_a = [1, 2, 3, 4]
vector_a = [1 2 3 4]


# 2 NOVEMBER 2023

## Numpy

In [ ]:
import numpy as np

list_a = [1,2,3,4]
vector_a = np.array([1,2,3,4])

print(list_a)
print(f"list_a = {list_a}")

print(vector_a)
print(f"vector_a = {vector_a}")
print(f"dikuadratkan = {vector_a**2}")

# contoh lain
matrix_b = np.array([(1,2),(3,4)])
print(f"matrix b = \n{matrix_b}")
print(f"matrix b^2 = \n{matrix_b**2}")

# contoh zeros (meng-0 kan sisi matrix)

zeros_c = np.zeros((2,2))
print(f"zeros c = \n{zeros_c}")

# ones

ones_d = np.ones((2,2))
print(f"zeros c = \n{ones_d}")

print("PENJUMLAHAN MATRIX")
# penjumlahan matrix

jumlah = matrix_b + matrix_b**2 + ones_d
print(jumlah)

[1, 2, 3, 4]
list_a = [1, 2, 3, 4]
[1 2 3 4]
vector_a = [1 2 3 4]
dikuadratkan = [ 1  4  9 16]
matrix b = 
[[1 2]
 [3 4]]
matrix b^2 = 
[[ 1  4]
 [ 9 16]]
zeros c = 
[[0. 0.]
 [0. 0.]]
zeros c = 
[[1. 1.]
 [1. 1.]]
PENJUMLAHAN MATRIX
[[ 3.  7.]
 [13. 21.]]


## Pygame

In [ ]:
import pygame

# init
pygame.init()
# variable running game
isRun = True

# membuat display surface object
window = pygame.display.set_mode((500,500))

# object game
# posisi
x = 250
y = 250

# ukuran
panjang = 20
lebar = 20

# kecepatan gerak
speed = 10

while isRun:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            isRun = False

    # update asset
    window.fill((255,255,255))
    # render ke display
    pygame.display.update()

pygame.quit()

# user input, database input
# update asset
# render ke display

KeyboardInterrupt: ignored

## __main__ sebagai gerbang program

In [ ]:
# fungsi main adalah untuk mendeklarasikan program utama

def fungsi_tambah(a:int,b:int)->int:
  return a+b

# fungsi utama
if __name__ == "__main__":
  angka1 = 5
  angka2 = 10
  hasil = fungsi_tambah(angka1,angka2)
  print(f"hasil tambah = {hasil}")

hasil tambah = 15


## Read External File

In [23]:
file = open("data_1.txt",mode="r")

#print(f"status read " {file.readable()}")
#print(f"status write " {file.writeable()}")

# baca seluruh file
print(file.read())

# baca per baris
print(file.readline(), end="") # baca baris pertama
print(file.readline(), end="") # baca baris kedua

# baca semua baris sebagai list
print(file.readlines())

print(f"apakah file sudah diclose : {file.closed}")
file.close()
print(f"apakah file sudah diclose : {file.closed}")

# salah satu teknik membuka file di python

print("\n",3*"=", " Membaca file txt dengan with", 3*"=")

with open("data_1.txt",mode="r") as file:
  content = file.readline()
  print(content,end="")
  print(f"apakah file sudah diclose : {file.closed}")

print(f"apakah file sudah diclose : {file.closed}")



jon si jhonny
[]
apakah file sudah diclose : False
apakah file sudah diclose : True

 ===  Membaca file txt dengan with ===
jon si jhonnyapakah file sudah diclose : False
apakah file sudah diclose : True


## Write External Data

In [26]:
# 1. mode write

with open("data_2.txt",'w',encoding="utf-8") as file:
  file.write("anjay\n")

# 2. mode append

with open("data_2.txt",'a',encoding="utf-8") as file:
  file.write("mabar")

# 3. mode r+

with open("data_2.txt",'r+',encoding="utf-8") as file:
  file.write("menambah dengan r+") # menimpa file


## Exception, Error, Try, Except

In [31]:
# contoh sederhana untuk menangkap exception
from math import nan

input_user = int(input("masukkan angka: "))
hasil = nan

try:
  hasil = 10/input_user
except:
  print("input tidak boleh 0")

print(f"hasil = {hasil}")

masukkan angka: 1
hasil = 10.0


In [32]:
# contoh di aplikasi
while(True):
  angka = int(input("masukan angka pembagi: "))
  try:
    hasil = 10/angka
    print(f"hasil = {hasil}")
    is_done = input("lanjutkan (y/n)? ")
    if is_done == "n":
      break
  except:
    print("pembagi nol, silahkan masukkan input lagi!")

print("Akhir dari program")

masukan angka pembagi: 10
hasil = 1.0
lanjutkan (y/n)? y
masukan angka pembagi: 0
pembagi nol, silahkan masukkan input lagi!
masukan angka pembagi: 10
hasil = 1.0
lanjutkan (y/n)? n
Akhir dari program


In [33]:
# contoh aplikasi untuk membuat file data.txt

try:
  with open("data.txt",'r') as file:
    print(file.read())
except:
  print("file data.txt tidak ditemukan, membuat file baru")
  with open("data.txt",'w',encoding='utf-8') as file:
    file.write("file baru")

print("akhir dari program")

file data.txt tidak ditemukan, membuat file baru
akhir dari program


contoh membuat exception

In [38]:
from numbers import Number

def tambah(a,b):
  if not isinstance(a,Number) or not isinstance(b,Number):
    raise "input harus angka"
  return a+b

print(tambah(5,"v"))

# akan keluar alert "input harus angka"

TypeError: ignored

contoh lain cara print error

In [39]:
angka = 0

try:
  hasil = 10/angka
except ZeroDivisionError as error_message:
  print(error_message)

division by zero
